# 数据操作

In [1]:
import torch

In [2]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [3]:
x.shape

torch.Size([6])

In [4]:
x.numel()

6

In [5]:
X = x.reshape(2,3)
X

tensor([[0, 1, 2],
        [3, 4, 5]])

In [6]:
torch.zeros((1,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
x = torch.tensor([1,2,8])
y = torch.tensor([2,2,2])

In [9]:
x + y

tensor([ 3,  4, 10])

In [10]:
x - y

tensor([-1,  0,  6])

In [11]:
x * y

tensor([ 2,  4, 16])

In [12]:
x / y

tensor([0.5000, 1.0000, 4.0000])

In [13]:
x ** y

tensor([ 1,  4, 64])

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 2.9810e+03])

In [15]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1 ,4 ,3],[1, 2, 3, 4],[4, 3, 2, 1]])

In [16]:
torch.cat((X,Y),dim=0) # 按行拼接

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [17]:
torch.cat((X,Y),dim=1) # 按列拼接

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [18]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
X.sum()

tensor(66.)

广播机制(Broadcasting Mechanism)

维度对齐：从最右边的维度开始向左比较
维度兼容：每个维度必须满足其一
维度大小相等
其中一该维度大小为1，则可以广播到另一个数组的大小
其中张量数组缺少该维度，可以添加大小为1的维度

In [20]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a + b # 3 by 2

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [23]:
before = id(Y) # 内存地址
Y = Y + X
id(Y) == before # 分配新地址

False

In [24]:
# 执行原地操作:不分配新内存
Z = torch.zeros_like(Y)
print('id(Z)',id(Z))
Z[:] = X + Y
print('id(Z)',id(Z))

id(Z) 1936084581536
id(Z) 1936084581536


In [25]:
before = id(Y) 
Y += X
id(Y) == before # 减少内存开销

True

In [26]:
before = id(Y) 
Y[:] =  Y + X
id(Y) == before # 

True

In [27]:
a = torch.tensor([1, 2, 3, 4])
b = torch.zeros_like(a)
b = a.clone() # 分配新内存，将 a 的一个副本分配给 b
b[0] = 10 # b 改变不影响 a
a, b

(tensor([1, 2, 3, 4]), tensor([10,  2,  3,  4]))

In [28]:
a = torch.tensor([1, 2, 3, 4])
b = torch.zeros_like(a)
b_copied = b.copy_(a) # 复制
b[0] = 10 # 修改 b 不影响 a ,影响 b_copied
a, b, b_copied

(tensor([1, 2, 3, 4]), tensor([10,  2,  3,  4]), tensor([10,  2,  3,  4]))

In [29]:
a = torch.tensor([1, 2, 3, 4])
b = a.expand(2,4)
b[0][0] = 10 # 修改 b 影响 a
a, b

(tensor([10,  2,  3,  4]),
 tensor([[10,  2,  3,  4],
         [10,  2,  3,  4]]))

In [30]:
a = torch.tensor([1, 2, 3, 4])
b = a[1:5]   # 切片
b[0] = 10    # 修改 b 影响 a
a, b

(tensor([ 1, 10,  3,  4]), tensor([10,  3,  4]))

In [31]:
a = torch.tensor([1, 2, 3, 4])
b = a.view(torch.numel(a)) # 视图
b[0] = 10    # 修改 b 影响 a
a, b

(tensor([10,  2,  3,  4]), tensor([10,  2,  3,  4]))

In [32]:
a = torch.tensor([1, 2, 3, 4])
b = a.add_(1) # 原地加 1，修改 b 影响 a
a, b

(tensor([2, 3, 4, 5]), tensor([2, 3, 4, 5]))

In [33]:
a = torch.tensor([1, 2, 3, 4])
b = a.mul_(2) # 原地乘 2，修改 b 影响 a
a, b

(tensor([2, 4, 6, 8]), tensor([2, 4, 6, 8]))

In [34]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [35]:
a = torch.tensor([1.5])
a, a.item(), float(a), int(a)

(tensor([1.5000]), 1.5, 1.5, 1)

# 数据预处理

In [36]:
import os

创建一个人工数据集，存储在.csv文件
CSV(Comma-Separated Values)文件，中文叫逗号分隔值文件，是一种非常简单、通用的纯文本格式，用来存储表格数据

逗号分隔不同的数据字，,换行符来分隔每一行数据

In [37]:
os.makedirs(os.path.join('D:/Python_study/DL_1','houseData'),exist_ok=True) # 创建目录
data_file = os.path.join('D:/Python_study/DL_1','houseData','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Ally,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [38]:
import pandas as pd

In [39]:
data = pd.read_csv(data_file)
data

,NumRooms,Ally,Price
0,NaN,Pave,127500
1,2.0,NaN,106000
2,4.0,NaN,178100
3,NaN,NaN,140000


In [40]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
numeric_cols = inputs.select_dtypes(include=['number']).columns
inputs[numeric_cols] = inputs[numeric_cols].fillna(inputs[numeric_cols].mean())
print(inputs)

   NumRooms  Ally
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [41]:
inputs = pd.get_dummies(inputs,dummy_na=True) # 独热编码，分类变量
# dummy_na=True 缺失值创建一个单独的虚拟列
print(inputs)

   NumRooms  Ally_Pave  Ally_nan
0       3.0       True     False
1       2.0      False      True
2       4.0      False      True
3       3.0      False      True


In [42]:
type(inputs.values)

numpy.ndarray

In [43]:
inputs = inputs.astype(float)
outputs = outputs.astype(float)
X, y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

# 线性代数

In [44]:
A = torch.arange(12,dtype=torch.float32).reshape((3,4))
A, A.T # Transpose

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  4.,  8.],
         [ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.]]))

In [45]:
A = torch.arange(12,dtype=torch.float32).reshape((3,4))
C = A[:]
C[0][0] = 1.5
A, C

(tensor([[ 1.5000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000]]),
 tensor([[ 1.5000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000]]))

In [46]:
# 哈达玛积(Hadamard Product)
# 按元素乘
A = B = torch.arange(12,dtype=torch.float32).reshape((3,4))
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [47]:
A = torch.arange(12,dtype=torch.float32).reshape((3,4))

In [48]:
A_sum_axis0 = A.sum(axis=0) # 遍历行的sum，丢失axis=0的维度
A_sum_axis0, A_sum_axis0.shape, A / A_sum_axis0

(tensor([12., 15., 18., 21.]),
 torch.Size([4]),
 tensor([[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]]))

In [49]:
A_sum_axis0 = A.sum(axis=0, keepdims=True)
# keepdims=True保持求和的维度，大小为 1
A_sum_axis0, A_sum_axis0.shape, A / A_sum_axis0

(tensor([[12., 15., 18., 21.]]),
 torch.Size([1, 4]),
 tensor([[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]]))

In [50]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.]])

In [51]:
x = torch.tensor([0, 1, 2, 3],dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
A = torch.arange(12,dtype=torch.float32).reshape((3,4))
B = torch.arange(12,dtype=torch.float32).reshape((4,3))
A.shape, B.shape, x.shape, y.shape

(torch.Size([3, 4]), torch.Size([4, 3]), torch.Size([4]), torch.Size([4]))

In [52]:
v = torch.dot(x,y)
v, v.shape

(tensor(6.), torch.Size([]))

In [53]:
Y = torch.mv(A,x) # Y = Ax
Y, Y.shape

(tensor([14., 38., 62.]), torch.Size([3]))

In [54]:
Z = torch.mm(A,B)
Z, Z.shape

(tensor([[ 42.,  48.,  54.],
         [114., 136., 158.],
         [186., 224., 262.]]),
 torch.Size([3, 3]))

In [55]:
# L2范数
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [56]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [57]:
# 佛罗贝尼乌斯范数(Frobenius Norm)
X = torch.ones((4,9))
torch.norm(X) # root sum square of all elements

tensor(6.)